site_name: "chefs-techdocs"
site_description: "CHEFS Technical Documentation"
docs_dir: "docs"
plugins:
  - techdocs-core
  - ezlinks

markdown_extensions:
  - attr_list
  - markdown_inline_mermaid
  - md_in_html
  - mkpatcher:
      location: patcher.py
nav:
  - About CHEFS: About.md
  - Roadmap: About/Product-Roadmap.md
  - Capabilities:
      - Functionalities: Capabilities/Functionalities.md
      - Integrations: Capabilities/Integrations.md
      - Accessibility: Capabilities/Accessibility.md
      - Form Management: Capabilities/Form-Management.md
      - Data Management: Capabilities/Data-Management.md
      - Architecture & State Management: Capabilities/Architecture-&-State-Management.md
  - Components:
      - Form Builder Components: Components/Form-Builder.md
      - Custom Components: Components/Custom.md
      - Examples of CHEFS forms and features: Components/Examples.md
  - Developer:
      - Contributors: Developer/Contributors.md
      - Deployment: Developer/Deployment.md
      - Form.io: Developer/Form.io.md
