site_name: "chefs-techdocs"
site_description: "CHEFS Technical Documentation"
docs_dir: "docs"
plugins:
  - techdocs-core
  - ezlinks

markdown_extensions:
  - attr_list
  - markdown_inline_mermaid
  - md_in_html
  - mkpatcher:
      location: patcher.py
nav:
  - About CHEFS: About-CHEFS.md
  - Roadmap: Product-Roadmap.md
  - Capabilities:
      - Functionalities: Capabilities/Functionalities.md
      - Integrations: Capabilities/Integrations.md
      - Accessibility: Capabilities/Accessibility.md
      - Form Management: Capabilities/Form-Management.md
      - Data Management: Capabilities/Data-Management.md
      - Architecture & State Management: Capabilities/Architecture-&-State-Management.md
  - Components:
      - Form Builder Components: Form-Builder-Components.md
      - Custom Components: Custom-components.md
      - Examples of CHEFS forms and features: Examples-of-CHEFS-forms-and-features.md
  - Developer:
      - Contributors: Contributors.md
      - Deployment: Deployment.md
      - Form.io: Form.io.md
      - Developer Additional Resources: Developer-Additional-Resources.md
