site_name: "chefs-techdocs"
site_description: "CHEFS Technical Documentation"
docs_dir: "docs"
plugins:
  - techdocs-core
  - ezlinks

markdown_extensions:
  - markdown_inline_mermaid
  - md_in_html
  - mkpatcher:
      location: patcher.py
nav:
  - Home: Home-Backup-page.md
  - About CHEFS: About-CHEFS.md
  - Roadmap: Product-Roadmap.md
  - CHEFS Capabilities:
      - Functionalities: CHEFS-functionalities.md
      - Integrations: Integrations.md
      - Accessibility: Accessibility.md
      - Form Management: Form-Management.md
      - Data Management: Data-Management.md
      - Architecture & State Management: Architecture-&-State-Management.md
  - CHEFS Components:
      - Form Builder Components: Form-Builder-Components.md
      - Custom Components: Custom-Components.md
      - Examples of CHEFS forms and features: Examples-of-CHEFS-forms-and-features.md
  - Developer:
      - Contributors: Contributors.md
      - Deployment: Deployment.md
      - Form.io: Form.io.md
      - Developer Additional Resources: Developer-Additional-Resources.md
